Create works section
Bavon101/my_portfolio pull request #2
Opened 2022-01-06 14:36 UTC by Bavon101

- Added work section view
- Styled work section 
- Added about-me section 
- Styled about-me section

2022-01-06 15:35 UTC, ahmetbozaci requested changes
# STATUS: Changes Required  ♻️

### Hello @Bavon101  ✋🏼 
#### Your project is great. You are almost done. However, there are some issues you should fix. Please fix them then your project will be approved.

___ 

### 💯  Nice to have 💯
- Your git-flow is correct. ✔️
- You set up linter files and no errors. ✔️
- Your pull request is very professional. It has a meaningful title and summary. Keep it up.✔️
- You stick to the design.✔️
- You know how to use flexbox very well.✔️
- You use HTML semantic elements correctly.✔️

___


### ♻️ Request changes ♻️
 - [ ] You should update the license on your README file. It is a broken link.
- [ ] _Check the comments under the review._

___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
- [ ] Your commit messages should always start with capital letters and you should write an **imperative** tense. I see you use imperative tense. I write it as optional. But this is a [general requirement](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md#:~:text=The%20commit%20message%20should%20be%20written%20in%20the%20imperative%20tense%20and%20capitalized) for every project. So you should pay attention to this for your next projects.
Instead of writing `'Added style' or Created the file`' you should write `Add style'  or 'Create the file'`

**OPTIONAL**
- [ ] You can change them by using `git rebase`. If you want to know how to change ı leave a few resources. 
- [Video - How to change commit messages](https://www.loom.com/share/00771f369b7b47fc968c019ecf0d3ba6)
- [Article - How to create good commit messages](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8/)

___

### Cheers and Happy coding! 💻 👏

![almost](https://media.giphy.com/media/3ohzAj9sRN1Ehl06Gc/giphy.gif)

___

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_


_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mentioning me as [ahmetbozaci](https://github.com/ahmetbozaci), I will receive a notification and will respond._
___
[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2022-01-06 15:35 UTC, ahmetbozaci commented on index.html
> +			<h1 class="projects_label">
- [x] You have already one h1 tag on the page. The page should include only one [h1 tag](https://www.w3schools.com/tags/tag_hn.asp#:~:text=Note%3A%20Only%20use%20one%20%3Ch1%3E%20per%20page%20%2D%20this%20should%20represent%20the%20main%20heading/subject%20for%20the%20whole%20page.%20Also%2C%20do%20not%20skip%20heading%20levels%20%2D%20start%20with%20%3Ch1%3E%2C%20then%20use%20%3Ch2%3E%2C%20and%20so%20on.). Please change to another hx tag.
- [x] Also you are using 8 indent spaces. Please use 2 spaces. Check this [article](https://developers.google.com/style/html-formatting).

2022-01-06 15:35 UTC, ahmetbozaci commented on index.html
> +						Bavon's Portfolio
- [ ] The project title should be wrapped by hx tag. Please change it. Also, apply it to other project titles on the page.

2022-01-06 15:35 UTC, ahmetbozaci commented on index.html
> +						</p>
- [ ] This should be a button. Please change it. And apply button styling. (active, hover, pressed). Change it to others on the page.

2022-01-06 15:35 UTC, ahmetbozaci commented on index.html
> +						</div>
- [ ] The list of project technologies should be wrapped by the `ul` tag and each item wrapped by the `li` tag. **Please apply it to other projects too.**
- [ ] Languages are not centered as an original design. Please fix it.  
**Apply it to other projects too.**
![image](https://user-images.githubusercontent.com/38635158/148404426-40097237-c9fc-4bce-a3ac-3c334aa3ac4c.png)

### ORIGINAL
![image](https://user-images.githubusercontent.com/38635158/148404574-f70c4ab2-5cbc-4a87-b6f5-46ecb39499ab.png)

2022-01-06 15:35 UTC, ahmetbozaci commented on index.html
> +			</h1>
- [ ] You have already one h1 tag on the page. The page should include only one [h1 tag](https://www.w3schools.com/tags/tag_hn.asp#:~:text=Note%3A%20Only%20use%20one%20%3Ch1%3E%20per%20page%20%2D%20this%20should%20represent%20the%20main%20heading/subject%20for%20the%20whole%20page.%20Also%2C%20do%20not%20skip%20heading%20levels%20%2D%20start%20with%20%3Ch1%3E%2C%20then%20use%20%3Ch2%3E%2C%20and%20so%20on.). Please change to another hx tag.

2022-01-06 15:35 UTC, ahmetbozaci commented on index.html
> +				</h1>
- [ ] You have already one h1 tag on the page. The page should include only one [h1 tag](https://www.w3schools.com/tags/tag_hn.asp#:~:text=Note%3A%20Only%20use%20one%20%3Ch1%3E%20per%20page%20%2D%20this%20should%20represent%20the%20main%20heading/subject%20for%20the%20whole%20page.%20Also%2C%20do%20not%20skip%20heading%20levels%20%2D%20start%20with%20%3Ch1%3E%2C%20then%20use%20%3Ch2%3E%2C%20and%20so%20on.). Please change to another hx tag.

2022-01-06 15:35 UTC, ahmetbozaci commented on index.html
> +				</h1>
- [ ] You have already one h1 tag on the page. The page should include only one [h1 tag](https://www.w3schools.com/tags/tag_hn.asp#:~:text=Note%3A%20Only%20use%20one%20%3Ch1%3E%20per%20page%20%2D%20this%20should%20represent%20the%20main%20heading/subject%20for%20the%20whole%20page.%20Also%2C%20do%20not%20skip%20heading%20levels%20%2D%20start%20with%20%3Ch1%3E%2C%20then%20use%20%3Ch2%3E%2C%20and%20so%20on.). Please change to another hx tag.

2022-01-06 15:35 UTC, ahmetbozaci commented on index.html
> +				</h1>
- [ ] You have already one h1 tag on the page. The page should include only one [h1 tag](https://www.w3schools.com/tags/tag_hn.asp#:~:text=Note%3A%20Only%20use%20one%20%3Ch1%3E%20per%20page%20%2D%20this%20should%20represent%20the%20main%20heading/subject%20for%20the%20whole%20page.%20Also%2C%20do%20not%20skip%20heading%20levels%20%2D%20start%20with%20%3Ch1%3E%2C%20then%20use%20%3Ch2%3E%2C%20and%20so%20on.). Please change to another hx tag.

2022-01-06 15:35 UTC, ahmetbozaci commented on index.html
> +				</p>
- [ ] This should be a button. Please change it. And apply button styling. (active, hover, pressed).

2022-01-06 15:35 UTC, ahmetbozaci commented on index.html
> +				</ul>
- [ ] The list of languages is not the center of the area. You can see in the original design it is near to left. Please change it. Apply it to all of them.

![image](https://user-images.githubusercontent.com/38635158/148406051-11e54858-da76-4d4d-8b9d-c904afc5d233.png)
___
### ORIGINAL
![image](https://user-images.githubusercontent.com/38635158/148406107-147d1e71-ce9b-4605-ae04-185ee9eb5ff2.png)

2022-01-06 15:35 UTC, ahmetbozaci commented on styles.css
> +  display: flex;
### OPTIONAL
- [x] For DRY CSS you should combine duplicate properties. Example, you can create class `.d-flex { display: flex}` and use this class in HTML file.

- [More information about DRY principles](https://www.freecodecamp.org/news/7-important-tips-for-writing-better-css/) 

- [Html and css best practices in curriculum](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md)

2022-01-06 15:35 UTC, ahmetbozaci commented on index.html
> +		<section class="project_section">
- [ ] The original design has 6 projects card. You have only 2 projects. Please add 4 projects as an original design.
- [ ] Project section has to same with the main section. To stick to the design please fix it. [Requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md#:~:text=You%20must%20stick%20to%20the%20design%20as%20much%20as%20possible%20(e.g.%2C%20font%2C%20colors%2C%20images%2C%20tests%2C%20margins)%20using%20the%20templates%20in%20Figma.)
![image](https://user-images.githubusercontent.com/38635158/148408072-e0f19ed4-f6b8-4aa8-982a-d55a95bc3943.png)

____

### ORIGINAL
![image](https://user-images.githubusercontent.com/38635158/148407811-88c9bd60-092f-4e9f-8267-4fa03bae4836.png)

2022-01-06 15:35 UTC, ahmetbozaci commented on index.html
> +		<section class="about_section">
- [ ] About myself section width has to same with project section. Please fix it.

![image](https://user-images.githubusercontent.com/38635158/148407448-9b2efe53-633b-45d8-a31f-46e5b525b884.png)
___
### ORIGINAL
![image](https://user-images.githubusercontent.com/38635158/148407567-938cb632-16e5-4983-b1fc-5aa5b87fa7a7.png)

2022-01-07 09:02 UTC, micheaol requested changes
Hi @Bavon101 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 

 ## Required Changes ♻️
- _Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-07 09:02 UTC, micheaol commented on index.html
> +							</p>
Please ensure that the list of project technologies `(e.g., "JavasScript", "HTML" and "CSS")` are a list `ul` and each of them a `li` as requested by the previous reviewer. This is also part of the requirement.

2022-01-07 09:02 UTC, micheaol commented on index.html
> +						</div>
As requested by the previous reviewer, kindly center the languages. I think the reason for this is because you have an overflow which is causing this error. Kindly fix the overflow error and you will be good.

### Figma design:
![figma](https://user-images.githubusercontent.com/10332499/148516284-1bd70c7e-80a2-4eb9-952f-86c5756573fc.PNG)

### Your design: 
![your-design](https://user-images.githubusercontent.com/10332499/148516338-12f31084-0b55-48fb-b6e7-e6e2ac4cd109.PNG)

2022-01-07 09:02 UTC, micheaol commented on index.html
> +			<div class="my_langauges_card about_card">
As requested by the previous reviewer, please make the about section the same width as the projects section. I think the issue here is that for a section width you are using `width: 400px;` and for another, you are using `width:100%`. Please check this as this is one of the reasons for the overflow you have in the section. Kindly fix this.

2022-01-07 09:02 UTC, micheaol commented on index.html
> +				</ul>
Please ensure that the languages list is properly aligned as in the design as requested by the previous reviewer. I think if you can fix the overflow issue, you should be good.

2022-01-07 09:02 UTC, micheaol commented on index.html
> +						</div>
As requested by the previous reviewer, please add two more projects to your project section so as to have six (6) projects as in the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=23%3A9).

2022-01-07 09:19 UTC, Bavon101 commented on index.html
> +				</ul>
@micheaol the previous review highlighted that the Language section is not to be aligned at the center as I had done initially but more aligned at the start, please take a look at the images the previous review attached in the comment.

2022-01-07 09:32 UTC, micheaol commented on index.html
> +				</ul>
Hi @Bavon101 ,

That was a typo, which has been corrected. I apologize for the typo.

2022-01-07 11:29 UTC, HENRYKC24 approved these changes
# STATUS: APPROVED :heavy_check_mark: 
![Approved!](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)
## Hi @Bavon101:wave:, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-07 11:33 UTC, merged