Desktop version
Bavon101/my_portfolio pull request #5
Opened 2022-01-13 14:45 UTC by Bavon101

- [ ] Add Desktop geometry images to src
- [ ] Add desktop styling using media query
- [ ] Add hover animation to display project card
- [ ] Add desktop view in html sections

2022-01-13 16:25 UTC, Meltrust requested changes
Hi @Bavon101 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Your project is really beautiful 👏 , you are really close to perfection.  Just implement the small changes below in the comments and you will get it approved in no time!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-13 16:25 UTC, Meltrust commented on index.html
> +		<header class="header">
- [x] It seems that your fonts have not been imported.  That is why although you are declaring them on the CSS elements, they are not displaying correctly.  

Kindly go [here](https://fonts.google.com/specimen/Poppins), and choose all the font weights that you will need.  Then, on the right, you will get 3 `<links>`'s.  Paste them to the `<head>` section of your HTML file!

Do this for all the fonts that you need, not just "Poppins".  Look:

![image](https://user-images.githubusercontent.com/57421823/149363594-f951d590-3c93-484e-a80c-bbc57fc7413e.png)

Paste the 3 `<link>`'s here:

![image](https://user-images.githubusercontent.com/57421823/149363840-9a2ea3f3-0dec-4d5a-9573-3ff77b362774.png)


That way, all the fonts that you declared will work and actually render on the page 💪

2022-01-13 16:25 UTC, Meltrust commented on index.html
> +			<div class="project_card_macro">
- [ ] Impressive animation! Now let's align these popup language tags vertically centered like in the design. 💪 

![image](https://user-images.githubusercontent.com/57421823/149366319-b1216a93-a7b1-45d5-81f3-bcbfe1017180.png)

2022-01-13 16:25 UTC, Meltrust commented on index.html
> +			<div class="project_section_images">
- [ ] Some of these images are not aligned like in the Figma:

Your Implementation | Figma Design
:---:|:---:
![image](https://user-images.githubusercontent.com/57421823/149367570-2e975d9c-159a-476b-8fa1-8cb732ded09e.png) | ![image](https://user-images.githubusercontent.com/57421823/149367728-9c796496-5083-4af1-9253-5d1410bdda91.png)

Please kindly correct them, so they look like the design 💯

2022-01-13 16:25 UTC, Meltrust commented on index.html
> +			<h3 class="contact_title">
- [x] This section's background color is different than the one given in the Figma.  Let's correct it, so your project looks more consistent with its colors.

2022-01-14 10:56 UTC, Rustamxon7 approved these changes
## Hi @Bavon101  👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

![image](https://i.pinimg.com/originals/77/0e/b0/770eb057449582c44672b2d2d1cc39b6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-14 10:56 UTC, Rustamxon7 commented on styles.css
> +
## WELL DONE ✅😲
- [ ] [OPTIONAL] All the things are fixed from the last review 👏😀. I also have a little suggestion to help improve your design. I recommend changing the cursor to pointer 👆 when hovering buttons. **TIP 📌**: You can add `cursor: pointer:`

2022-01-14 12:05 UTC, merged